######################################################################
# Automatically generated by qmake (3.0) Tue Dec 27 14:07:22 2016
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
SOURCES += main.cpp
